//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_merit
    {
        public int merit_id { get; set; }
        public Nullable<int> m_applicant_id { get; set; }
        public Nullable<int> m_dep_id { get; set; }
        public Nullable<int> m_app_status_id { get; set; }
    
        public virtual applicant_status applicant_status { get; set; }
        public virtual tbl_depart tbl_depart { get; set; }
        public virtual tbl_student_reg tbl_student_reg { get; set; }
    }
}
